KLEI     1 return {
	override_enabled = true,
	worldgen_preset = "SURVIVAL_DEFAULT_PLUS",    -- "SURVIVAL_TOGETHER", "MOD_MISSING", "SURVIVAL_TOGETHER_CLASSIC", "SURVIVAL_DEFAULT_PLUS", "COMPLETE_DARKNESS", "DST_CAVE", "DST_CAVE_PLUS"
	settings_preset = "SURVIVAL_TOGETHER",
	overrides = {
	    -- MISC
  task_set = "default",    -- "classic", "default", "cave_default"
  start_location = "default",    -- "caves", "default", "plus", "darkness"
  world_size = "huge",    -- "small", "medium", "default", "huge"
  branching = "default",    -- "never", "least", "default", "most"
  loop = "default",    -- "never", "default", "always"
  autumn = "verylongseason",    -- "noseason", "veryshortseason", "shortseason", "default", "longseason", "verylongseason", "random"
  winter = "veryshortseason",    -- "noseason", "veryshortseason", "shortseason", "default", "longseason", "verylongseason", "random"
  spring = "longseason",    -- "noseason", "veryshortseason", "shortseason", "default", "longseason", "verylongseason", "random"
  summer = "longseason",    -- "noseason", "veryshortseason", "shortseason", "default", "longseason", "verylongseason", "random"
  season_start = "default",    -- "default", "winter", "spring", "summer", "autumnorspring", "winterorsummer", "random"
  day = "longday",    -- "default", "longday", "longdusk", "longnight", "noday", "nodusk", "nonight", "onlyday", "onlydusk", "onlynight"
  weather = "rare",    -- "never", "rare", "default", "often", "always"
  earthquakes = "default",    -- "never", "rare", "default", "often", "always"
  lightning = "rare",    -- "never", "rare", "default", "often", "always"
  frograin = "rare",    -- "never", "rare", "default", "often", "always"
  wildfires = "rare",    -- "never", "rare", "default", "often", "always"
  touchstone = "default",    -- "never", "rare", "default", "often", "always"
  regrowth = "veryfast",    -- "veryslow", "slow", "default", "fast", "veryfast"
  cavelight = "veryfast",    -- "veryslow", "slow", "default", "fast", "veryfast"
  boons = "default",    -- "never", "rare", "default", "often", "always"
  prefabswaps_start = "always",    -- "classic", "default", "highly random"
  prefabswaps = "max",    -- "none", "few", "default", "many", "max"

  -- RESOURCES
  flowers = "always",    -- "never", "rare", "default", "often", "always"
  grass = "always",    -- "never", "rare", "default", "often", "always"
  sapling = "always",    -- "never", "rare", "default", "often", "always"
  marshbush = "always",    -- "never", "rare", "default", "often", "always"
  tumbleweed = "always",    -- "never", "rare", "default", "often", "always"
  reeds = "always",    -- "never", "rare", "default", "often", "always"
  trees = "default",    -- "never", "rare", "default", "often", "always"
  flint = "default",    -- "never", "rare", "default", "often", "always"
  rock = "default",    -- "never", "rare", "default", "often", "always"
  rock_ice = "always",    -- "never", "rare", "default", "often", "always"
  meteorspawner = "default",    -- "never", "rare", "default", "often", "always"
  meteorshowers = "default",    -- "never", "rare", "default", "often", "always"
  mushtree = "default",    -- "never", "rare", "default", "often", "always"
  fern = "always",    -- "never", "rare", "default", "often", "always"
  flower_cave = "always",    -- "never", "rare", "default", "often", "always"
  wormlights = "always",    -- "never", "rare", "default", "often", "always"

  -- UNPREPARED
  berrybush = "always",    -- "never", "rare", "default", "often", "always"
  carrot = "always",    -- "never", "rare", "default", "often", "always"
  mushroom = "always",    -- "never", "rare", "default", "often", "always"
  cactus = "always",    -- "never", "rare", "default", "often", "always"
  banana = "always",    -- "never", "rare", "default", "often", "always"
  lichen = "always",    -- "never", "rare", "default", "often", "always"

  -- ANIMALS
  rabbits = "always",    -- "never", "rare", "default", "often", "always"
  moles = "default",    -- "never", "rare", "default", "often", "always"
  butterfly = "always",    -- "never", "rare", "default", "often", "always"
  birds = "always",    -- "never", "rare", "default", "often", "always"
  buzzard = "default",    -- "never", "rare", "default", "often", "always"
  catcoon = "default",    -- "never", "rare", "default", "often", "always"
  perd = "rare",    -- "never", "rare", "default", "often", "always"
  pigs = "often",    -- "never", "rare", "default", "often", "always"
  lightninggoat = "always",    -- "never", "rare", "default", "often", "always"
  beefalo = "often",    -- "never", "rare", "default", "often", "always"
  beefaloheat = "never",    -- "never", "rare", "default", "often", "always"
  hunt = "rare",    -- "never", "rare", "default", "often", "always"
  alternatehunt = "rare",    -- "never", "rare", "default", "often", "always"
  penguins = "always",    -- "never", "rare", "default", "often", "always"
  cave_ponds = "often",    -- "never", "rare", "default", "often", "always"
  ponds = "default",    -- "never", "rare", "default", "often", "always"
  bees = "default",    -- "never", "rare", "default", "often", "always"
  angrybees = "rare",    -- "never", "rare", "default", "often", "always"
  tallbirds = "always",    -- "never", "rare", "default", "often", "always"
  slurper = "rare",    -- "never", "rare", "default", "often", "always"
  bunnymen = "default",    -- "never", "rare", "default", "often", "always"
  slurtles = "default",    -- "never", "rare", "default", "often", "always"
  rocky = "default",    -- "never", "rare", "default", "often", "always"
  monkey = "default",    -- "never", "rare", "default", "often", "always"

  -- MONSTERS
  spiders = "default",    -- "never", "rare", "default", "often", "always"
  cave_spiders = "default",    -- "never", "rare", "default", "often", "always"
  hounds = "rare",    -- "never", "rare", "default", "often", "always"
  houndmound = "default",    -- "never", "rare", "default", "often", "always"
  merm = "default",    -- "never", "rare", "default", "often", "always"
  tentacles = "default",    -- "never", "rare", "default", "often", "always"
  chess = "default",    -- "never", "rare", "default", "often", "always"
  lureplants = "default",    -- "never", "rare", "default", "often", "always"
  walrus = "default",    -- "never", "rare", "default", "often", "always"
  liefs = "default",    -- "never", "rare", "default", "often", "always"
  deciduousmonster = "default",    -- "never", "rare", "default", "often", "always"
  krampus = "default",    -- "never", "rare", "default", "often", "always"
  bearger = "default",    -- "never", "rare", "default", "often", "always"
  deerclops = "default",    -- "never", "rare", "default", "often", "always"
  goosemoose = "rare",    -- "never", "rare", "default", "often", "always"
  dragonfly = "always",    -- "never", "rare", "default", "often", "always"
  bats = "default",    -- "never", "rare", "default", "often", "always"
  fissure = "rare",    -- "never", "rare", "default", "often", "always"
  worms = "default",    -- "never", "rare", "default", "often", "always"
	},
}
