name: build testing
on:
  pull_request:
jobs:
  linux:
    name: build testing
    runs-on: ubuntu-latest
    steps:
      - name: Build Ubuntu Latest
        run:  |
          pwd
          ls -la
          src/fyp_dist/build.sh

