name: build testing
on:
  pull_request:
jobs:
  linux:
    name: build testing
    runs-on: ubuntu-latest
    steps:
      - name: Build Ubuntu Latest
        run:  |
          ls -la ..
          cd .. && src/fyp_dist/build.sh

