name: Build Script Test

on:
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest # This is the default runner, but we'll override it in the matrix

    strategy:
      matrix:
        ubuntu_version: [ 'ubuntu-24.04', 'ubuntu-22.04', 'ubuntu-20.04' ] # Latest LTS and previous two LTS versions

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up environment for ${{ matrix.ubuntu_version }}
      run: |
        echo "Running on Ubuntu version: ${{ matrix.ubuntu_version }}"
        # Add any setup commands specific to your build environment if needed.
        # For example, installing dependencies:
        sudo apt update
        sudo apt install -y build-essential direnv cmake 

    - name: Run Build Script
      run: |
        ls -la
        cd src/fyp && ./build.sh
